version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: wowspelldle-api
    ports:
      - "5000:5052"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:5052
      - ConnectionStrings__DefaultConnection=Host=host.docker.internal;Database=WowSpellDle;Username=myuser;Password=mypassword
    restart: unless-stopped
